# Generated by Django 4.2.6 on 2023-10-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_planet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='name',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
