# Generated by Django 4.2.6 on 2023-10-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_hotspot_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planet',
            name='texture_file',
        ),
        migrations.AddField(
            model_name='planet',
            name='bump_map',
            field=models.FileField(blank=True, upload_to='static'),
        ),
        migrations.AddField(
            model_name='planet',
            name='color_map',
            field=models.FileField(default=None, upload_to='static'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planet',
            name='specular_map',
            field=models.FileField(blank=True, upload_to='static'),
        ),
    ]
