# Generated by Django 4.2.6 on 2023-10-04 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet_type', models.TextField(choices=[('Moon', 'Moon'), ('Planet', 'Planet'), ('Star', 'Star')])),
                ('size', models.CharField(max_length=300)),
                ('speed', models.CharField(max_length=300)),
                ('distance_to_closest_star', models.CharField(max_length=300)),
                ('average_surface_temperature', models.CharField(max_length=300)),
                ('texture_file', models.FileField(upload_to='')),
                ('systems', models.ManyToManyField(to='api.system')),
            ],
        ),
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.CharField(max_length=300)),
                ('latitude', models.CharField(max_length=300)),
                ('hotspot_type', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('popularity', models.TextField()),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.planet')),
            ],
        ),
    ]
