# Generated by Django 4.2.6 on 2023-10-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='systems',
            field=models.ManyToManyField(blank=True, to='api.system'),
        ),
    ]
