# Generated by Django 4.2.6 on 2023-10-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_planet_systems'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='ring_map',
            field=models.FileField(blank=True, default=None, null=True, upload_to='static'),
        ),
    ]
