# Generated by Django 4.2.6 on 2023-10-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_planet_ring_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
