# Generated by Django 4.2.6 on 2023-10-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_planet_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='overlay_map',
            field=models.FileField(blank=True, default=None, null=True, upload_to='static'),
        ),
    ]
